_BASE_: "../Base-RCNN-FPN.yaml"

MODEL:
  WEIGHTS: "/home/eric/FSCE_tea-diseases/checkpoints/coco/faster_rcnn/set1/split1/base/randinit/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101

  BACKBONE:
    FREEZE: False
    FREEZE_AT: 5

  PROPOSAL_GENERATOR:
    FREEZE: False
  RPN:
    POST_NMS_TOPK_TRAIN: 2000

  ROI_HEADS:
    NAME: "ContrastiveROIHeads"
    NUM_CLASSES: 17
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: False
    BATCH_SIZE_PER_IMAGE: 256
    # SCORE_THRESH_TEST: 0.0

  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      TEMPERATURE: 0.2
      LOSS_WEIGHT: 0.5
      DECAY:
        ENABLED: True
        STEPS: [6000, 10000]
        RATE: 0.5
      IOU_THRESHOLD: 0.8  # high credibility proposals provide consistency

DATASETS:
  TRAIN: ('trainval_tea',)
  TEST: ('test_tea',)

SOLVER:
  IMS_PER_BATCH: 3
  BASE_LR: 0.001
  GAMMA: 0.5
  STEPS: (8000,13000)
  MAX_ITER: 15000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 200

TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 3000

OUTPUT_DIR: "checkpoints/coco/faster_rcnn/set1/split1/30shot/"