_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 17
DATASETS:
  TRAIN: ('trainval_tea',)
  TEST: ('test_tea',)
SOLVER:
  BASE_LR: 0.01
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  WARMUP_ITERS: 500
  WARMUP_FACTOR: 0.001
  WARMUP_METHOD: "linear"